version: '3'

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d

  registry:
    image: registry:2
    restart: always
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
    env_file:
      - ./registry.env

  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - 8000:80
    env_file:
      - ./registry_ui.env
    container_name: registry-ui

volumes:
  nginx_secrets:
